### PR TITLE
Update logo and link for amundsen project

### PR DESCRIPTION
**Pull request by feng-tao**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by feng-tao** [comment]
Could we merge this Pr?

**Comment by feng-tao** [comment]
lgtm

**Comment by feng-tao** [comment]
LGTM

**Comment by dankohn** [comment]
We require logos to include the project name. We can modify this for you by adding the project name in Helvetica, or you are welcome to.

**Comment by feng-tao** [comment]
hey @dankohn , I am the owner of Amundsen project. the project has already been included in the landscape, but I found the logo is incorrect. This pr is to use the updated logo (https://github.com/lyft/amundsen/tree/master/docs/img/logos)

**Comment by feng-tao** [comment]
cc @ibrahimhaddad

**Comment by feng-tao** [comment]
@dankohn saw you update the logo in https://github.com/lfai/lfai-landscape/pull/192 for other project, could you did the same for Amundsen as well?

**Comment by ibrahimhaddad** [comment]
Hi @feng-tao , thanks for the contribution. As @dankohn mentioned, we require the logo to include the project name and not just be an icon. Can you please provide a logo that includes the icon and the project name? We can do it for you as well if you prefer. Thank you.

**Comment by feng-tao** [comment]
thanks @ibrahimhaddad , does https://raw.githubusercontent.com/lyft/amundsen/master/docs/img/logos/amundsen_logo_on_light.svg?sanitize=true work?

**Comment by dankohn** [comment]
Yes, that's fine. Could you update your PR, please?

**Comment by feng-tao** [comment]
@dankohn pr updated

**Pull request merged**
