### PR TITLE
fix for logos for adobe illustrator

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
No city for a crunchbase entry for cortex-dev at https://www.crunchbase.com/organization/cortex-dev

**Comment by AndreyKozlov1984** [comment]
@dankohn can you fix this ?

**Comment by dankohn** [comment]
Fixed, but you'll have to wait an hour for the cache to expire.

**Comment by AndreyKozlov1984** [comment]
Returning titles

**Comment by AndreyKozlov1984** [comment]
LGTM

**Pull request merged**
