### PR TITLE
added Catalyst

### PR DESCRIPTION
**Pull request by TezRomacH**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by TezRomacH** [comment]
Hey, guys. Do I understand correctly that the bot is arguing about the missing `city` field in CrunchBase?

**Comment by dankohn** [comment]
Yes. There’s a bug where it didn’t post the error to this thread. But, you just need to add the city to your Crunchbase entry, wait an hour for the Crunchbase cache you expire, and then post an empty commit to trigger a new build. Or ask and I can trigger it for you.

**Comment by TezRomacH** [comment]
Thank you :)

**Comment by dankohn** [comment]
I added Moscow and rebuilt and the preview is now live.

**Comment by TezRomacH** [comment]
It was very fast, thanks :D

demo looks fine

**Comment by TezRomacH** [comment]
LGTM

**Comment by TezRomacH** [comment]
ping :)

**Comment by TezRomacH** [comment]
Hey, guys. How are you doing?

Do you need anything else from me to make PR merged?

**Pull request merged**
